# Generated by Django 3.0.2 on 2020-02-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(default='test', max_length=255)),
                ('body_text', models.TextField(default='default')),
                ('pub_date', models.DateField(auto_now=True)),
                ('n_visits', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=200)),
                ('user_name', models.CharField(default='匿名', max_length=20)),
                ('kind', models.CharField(choices=[('python', 'python'), ('database', 'database'), ('economic', 'economic')], default=('python', 'python'), max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mytable',
            fields=[
                ('id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'mytable',
                'managed': True,
            },
        ),
    ]
