# Generated by Django 3.0.2 on 2020-02-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_by', models.TextField(max_length=1000)),
                ('comment', models.TextField(max_length=100)),
                ('article', models.IntegerField()),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PYnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('publisher', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
